### ISSUE TITLE
Use v3 branch instead of the tag

### ISSUE THREAD

**Issue by LitoMore** [kceb/git-message-action#19]
Currently, the `kceb/git-message-action@v3` only matches the https://github.com/kceb/git-message-action/releases/tag/v3.

You could create a branch named `v3` and delete the existing `v3` tag instead.

So that we can use `kceb/git-message-action@v3` to match all `v3.x.x` releases.

Remember to apply all changes to the `v3` branch when you release some new changes.

**Comment by kceb** [comment]
I've deleted the tag and pushed a `v3` branch.

@LitoMore I've also added you as a maintainer due to your recent contribution

**Comment by kceb** [comment]
I've deleted the tag and pushed a `v3` branch.

@LitoMore I've also added you as a maintainer due to your recent contribution
